Rubocop.yml

# Commonly used screens these days easily fit more than 80 characters.
Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

AllCops:
  Exclude:
    - bin/**/*
    - db/migrate/**.rb
    - db/seeds/**.rb
    - db/seeds.rb
    - db/schema.rb
    - client/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - test/test_helper.rb
    - config/**/*
    - lib/scraper/*
    - config.ru
    - Rakefile
